### ISSUE TITLE
Code errors

### ISSUE THREAD

**Issue by karmaBonfire** [SillyAsriel/githubPages-About#1]
Based on [this revision](https://github.com/SillyAsriel/githubPages-About/blob/6b3bcdc4b32db4203d7a6d97a9bb8bcd8cc7a187/index.html):

- [ ] Line 4: extra space in `<title>`
- [ ] Line 18: `<h1>` does not have a `color` property; use `style="{ ...; color: #3b3b43}"` instead
- [ ] Also line 18: `;` outside the style def.
- [ ] Line 21: `<p>` is opened but never closed
- [ ] Line 24: sourcing images from other servers is a bad idea (use your `assets` folder)

You might want to fix that

**Comment by uBIank** [comment]
Fixed. Thanks for your contribution.
